app/blog/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('9104da4ec86c28b6ee2bc84fb2870a659c170864/', admin.site.urls),
    path('', include('post.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/urls.py
from django.conf.urls import url

from .views import IndexView, PostView, PostEdit, PostDelete

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^index/$', IndexView.as_view()),
    url(r'^post/(?P<slug>[-\w]+).html/$', PostView.as_view(), name='post-view'),
    url(r'^post-edit/(?P<slug>[-\w]+).html/$', PostEdit.as_view(), name='post-edit'),
    url(r'^post-delete/(?P<slug>[-\w]+).html/$', PostDelete.as_view(), name='post-delete'),
]

app/post/urls.py
from django.urls import path, re_path
from .views import IndexView, PostView, SearchView#, AboutView, ContactsView

app_name = 'post'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search', SearchView.as_view(), name='search'),
    #url(r'^index/$', IndexView.as_view()),
    #url(r'^about/$', AboutView.as_view()),
    #url(r'^contacts/$', ContactsView.as_view()),
    re_path(r'^post/(?P<slug>[-\w]+).html$', PostView.as_view(), name='post'),
]

app/dashboard/models.py
from django.db import models
from django.forms import forms
from post.models import Post

#class PostForm(forms.ModelForm):

# Create your models here.

app/post/models.py
from django.db import models
from django.utils import timezone
import markdown 
from elasticsearch_dsl import Document, Text, Short

from blog.settings import ES_INDEX_NAME


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField("Название", max_length=255, unique=True)
    slug = models.SlugField("ЧПУ", max_length=255, unique=True)
    excerpt = models.TextField("Выдержка")
    # minutes_to_read = models.IntegerField("ETA")
    body = models.TextField("Текст", blank=True)
    markdown = models.TextField("Markdown")
    minutes_to_read = models.IntegerField("Minutes to read")
    created_at = models.DateTimeField("Создано", auto_now_add=True)
    updated_at = models.DateTimeField("Обновлено", auto_now=True)
    published_at = models.DateTimeField("Опубликовано", default=timezone.now)
    status = models.CharField("Статус", max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    @property
    def views(self):
        return ViewCount.objects.filter(post=self).count()

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ('-published_at',)

    def publish(self):
        self.published_at = timezone.now()
        self.status = 'published'
        super(Post, self).save()

    def save(self, *args, **kwargs):
        self.body = markdown.markdown(self.markdown, extensions=['markdown.extensions.extra', 'markdown.extensions.nl2br', 'markdown.extensions.sane_lists'])
        super(Post, self).save(*args, **kwargs)

    def increment_view_counter(self, ip):
        ViewCount(post=self, ip=ip).save()

    def __str__(self):
        return self.title

    def indexing(self):
        obj = PostType(
            meta={'id': self.id},
            published_at=self.published_at.strftime("%b, %d %Y"),
            title=self.title,
            text=self.body,
            excerpt=self.excerpt,
            slug=self.slug,
            minutes_to_read=self.minutes_to_read,
        )
        obj.save()
        return obj.to_dict(include_meta=True)


class PostType(Document):
    published_at = Text()
    title = Text()
    body = Text()
    excerpt = Text()
    slug = Text()
    minutes_to_read = Short()

    class Index:
        name = ES_INDEX_NAME


class ViewCount(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField()
    first_visit_date = models.DateTimeField("Первый просмотр", auto_now_add=True)

app/dashboard/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from post.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    return HttpResponse('Index function view')

class IndexView(View):
    def get(self, request):
        posts = Post.published.all()
        paginator = Paginator(posts, 3)
        page = request.GET.get('page')

        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        return render(request, 'dashboard/post/index.html', {'posts': posts})


class PostView(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        return render(request, 'dashboard/post/view.html', {'post': post})

class PostEdit(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        return render(request, 'dashboard/post/edit.html', {'post': post})

class PostDelete(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        return render(request, 'dashboard/post/delete.html', {'post': post})

class PostCreate(View):
    def get(self, request):
        post = Post()
        return render(request, 'dashboard/post/create.html', {'post': post})

app/post/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Post, ViewCount
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .search import search
# including Mako template engine dependencies
from mako.template import Template
from mako.lookup import TemplateLookup
from blog.settings import TEMPLATES, BASE_DIR
import os

PAGE_SIZE = 8

class IndexView(View): 
    def get(self, request):
        posts = Post.published.all()
        paginator = Paginator(posts, PAGE_SIZE)
        page = request.GET.get('page')

        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        template_dirs = [os.path.join(BASE_DIR, 'post/templates/post'), os.path.join(BASE_DIR, 'templates')]
        page_lookup = TemplateLookup(directories=template_dirs)
        page_tempalte = Template(filename=os.path.join(BASE_DIR, 'post/templates/post/index_mako.html'), lookup=page_lookup)
        context = dict(
            posts=posts,
            query=''
        )

        return HttpResponse(page_tempalte.render(**context))
        #return render(request, 'post/index.html', {'posts': posts})


class SearchView(View):
    def get(self, request):
        query = request.GET.get('q')
        if query.strip:
            responseObject = search(query)
            hits = responseObject.hits
            message = "Found " + str(len(hits)) + "matches"
        else:
            hits = []
            message = "Please, input something to search for."

        return render(request, 'post/search.html', {
            'posts': hits,
            'message': message,
            'query': query
        })


class PostView(View):

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)

        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[-1].strip()
        else:
            ip = request.META.get('REMOTE_ADDR')
        try:
            ViewCount.objects.get(ip_address=ip, post=post)
        except ViewCount.DoesNotExist:
            ViewCount(post=post, ip_address=ip).save()

        return render(request, 'post/post.html', {'post': post})


class AboutView(View):
    def get(self, request):
        return render(request, 'post/about.html')


class ContactsView(View):
    def get(self, request):
        return render(request, 'post/contacts.html')

app/dashboard/templates/dashboard/post/edit.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'post/css/blog-post.css' %}" rel="stylesheet">
{% endblock %}
<h1>Редактирование поста</h1>
{% block content %}
    form

{% endblock %}

app/dashboard/templates/dashboard/post/index.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'post/css/blog-home.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

    {% for post in posts %}

        <h2>
            <a href="{% url 'dashboard:post-view' post.slug %}">{{ post.title }}</a>
        </h2>
        <p><span class="glyphicon glyphicon-time"></span> Опубликовано {{ post.published_at|date:"d-m-Y" }}
            в {{ post.published_at|time }}</p>

        <p>{{ post.body|truncatewords_html:15 }}</p>
        <a class="btn btn-primary" href="{% url 'dashboard:post-view' post.slug %}">Подробнее <span
                class="glyphicon glyphicon-chevron-right"></span></a>
        <a class="btn btn-default" href="{% url 'dashboard:post-edit' post.slug %}">Редактировать</a>
        <a class="btn btn-default" href="{% url 'dashboard:post-delete' post.slug %}">Удалить</a>

        <hr>


    {% empty %}
        <p>Здесь еще ничего нет, попрубуйте зайти позже.</p>
    {% endfor %}

{% endblock %}

{% block pager %}
<ul class="pager">

        {% if posts.has_previous %}
            <li><a class="prev" href="?page={{ posts.previous_page_number }}">Назад</a></li>
        {% endif %}

        <li class="active">
            <span>Страница {{ posts.number }} из {{ posts.paginator.num_pages }}</span>
        </li>

        {% if posts.has_next %}
            <li><a class="next" href="?page={{ posts.next_page_number }}">Вперед</a></li>
        {% endif %}

</ul>
{% endblock %}

app/dashboard/templates/dashboard/post/view.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'post/css/blog-post.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1 class="">
        {{ post.title }}

    </h1>
    <div class="post-meta">
        <div class="post-date">
            Опубликовано {{ post.published_at|date:"M, d Y" }}
        </div>
        <div class="post-pageviews"></div>
        <div class="post-tags"></div>
    </div>

    <p>{{ post.body|linebreaks }}</p>

{% endblock %}

app/post/templates/_post/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About Page</h1>
{% endblock %}

app/post/templates/_post/contacts.html
{% extends 'base.html' %}
{% block content %}
    <h1>Contacts Page</h1>
{% endblock %}

app/post/templates/_post/index.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'post/css/blog-home.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}

    {% for post in posts %}

        <h2>
            <a href="{% url 'post:post' post.slug %}">{{ post.title }}</a>
        </h2>
        <p><span class="glyphicon glyphicon-time"></span> Опубликовано {{ post.published_at|date:"d-m-Y" }}
            в {{ post.published_at|time }}</p>

        <p>{{ post.body|truncatewords_html:15 }}</p>
        <a class="btn btn-primary" href="{% url 'post:post' post.slug %}">Подробнее <span
                class="glyphicon glyphicon-chevron-right"></span></a>

        <hr>


    {% empty %}
        <p>Здесь еще ничего нет, попрубуйте зайти позже.</p>
    {% endfor %}

{% endblock %}

{% block pager %}
<ul class="pager">

        {% if posts.has_previous %}
            <li><a class="prev" href="?page={{ posts.previous_page_number }}">Назад</a></li>
        {% endif %}

        <li class="active">
            <span>Страница {{ posts.number }} из {{ posts.paginator.num_pages }}</span>
        </li>

        {% if posts.has_next %}
            <li><a class="next" href="?page={{ posts.next_page_number }}">Вперед</a></li>
        {% endif %}

</ul>
{% endblock %}

app/post/templates/_post/post.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'post/css/blog-post.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <h1 class="">
        {{ post.title }}

    </h1>
    <div class="post-meta">
        <div class="post-date">
            Опубликовано {{ post.published_at|date:"M, d Y" }}
        </div>
        <div class="post-pageviews"></div>
        <div class="post-tags"></div>
    </div>

    <p>{{ post.body|safe }}</p>

{% endblock %}

app/post/templates/post/index.html
{% extends 'base.html' %} 

{% block title %}IT blog of Maksim Manylow, web-dev{% endblock %}
{% block description %}Articles about linux server administration, web development and other things{% endblock %}
{% block content %}
<div id="content" class="page-index">

    <div id="search_bar">
        <form class="form-inline mt-2 mt-md-0 search-form" action="/search">
            <input name="q" class="search-form-input form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" value="{{ query }}">
        </form>
    </div>

  {% for post in posts %}

  <a class="post-link" href="{% url 'post:post' post.slug %}">
    <article class="post">
      <!--
      <div class="post-image">
        <svg viewBox="0 0 18 7">
          <path fill="#CB3837" d="M0,0v6h5v1h4v-1h9v-6"></path>
          <path fill="#FFF" d="M1,1v4h2v-3h1v3h1v-4h1v5h2v-4h1v2h-1v1h2v-4h1v4h2v-3h1v3h1v-3h1v3h1v-4"></path>
        </svg>
      </div>
    -->
      <div class="post-info">
        <h2 class="post-title">{{ post.title }}</h2>
        <div class="post-meta">
          <span class="post-meta-date">{{ post.published_at|date:"M, d Y" }}</span>
          <span class="post-meta-time-to-read">{{ post.minutes_to_read }} min read</span>
        </div>
        <div class="post-excerpt">{{ post.excerpt }}</div>
        <div class="post-tags"></div>
      </div>
    </article>
  </a>

  {% empty %}
  <p>Nothing is published yet.</p>
  {% endfor %}
  {% if posts.paginator.num_pages > 1 %}
  {% block pager %}

  <nav aria-label="pagination">
      <ul class="pagination justify-content-center">

      {% if posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
      {% endif %}

      {% for i in posts.paginator.page_range %}

        {% if posts.number == i %}
          <li class="page-item active"><a class="page-link">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}

      {% endfor %}


      {% if posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Next</a>
        </li>
      {% endif %}


      </ul>
    </nav>
  {% endblock %}
  {% endif %}
</section>
{% endblock %}

app/post/templates/post/index_mako.html
<%! import datetime %>
<%inherit file="/base_mako.html"/>
<%block name="title">
    IT blog of Maksim Manylow, web-dev
</%block>
<%block name="description">
    Articles about linux server administration, web development and other things
</%block>

<%block name="content">
    <div id="content" class="page-index">

        <div id="search_bar">
            <form class="form-inline mt-2 mt-md-0 search-form" action="/search">
                <input name="q" class="search-form-input form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" value="${query}">
            </form>
        </div>

        % if len(posts):
              % for post in posts:

                  <a class="post-link" href="/post/${ post.slug }.html">
                    <article class="post">
                      <!--
                      <div class="post-image">
                        <svg viewBox="0 0 18 7">
                          <path fill="#CB3837" d="M0,0v6h5v1h4v-1h9v-6"></path>
                          <path fill="#FFF" d="M1,1v4h2v-3h1v3h1v-4h1v5h2v-4h1v2h-1v1h2v-4h1v4h2v-3h1v3h1v-3h1v3h1v-4"></path>
                        </svg>
                      </div>
                    -->
                      <div class="post-info">
                        <h2 class="post-title">${post.title}</h2>
                        <div class="post-meta">
                          <span class="post-meta-date">${ post.published_at.strftime("%B, %d %Y") }</span>
                          <span class="post-meta-time-to-read">${post.minutes_to_read} min read</span>
                        </div>
                        <div class="post-excerpt">${post.excerpt}</div>
                        <div class="post-tags"></div>
                      </div>
                    </article>
                  </a>

            % endfor
        % else:
            <p>Nothing is published yet.</p>
        % endif

      % if posts.paginator.num_pages > 1:
      <%block name="pager">

          <nav aria-label="pagination">
              <ul class="pagination justify-content-center">

              % if posts.has_previous:
                <li class="page-item">
                  <a class="page-link" href="?page=${posts.previous_page_number}">Previous</a>
                </li>
              % else:
                <li class="page-item disabled">
                  <a class="page-link">Previous</a>
                </li>
              % endif

              % for i in posts.paginator.page_range:

                % if posts.number == i:
                  <li class="page-item active"><a class="page-link">${i}</a></li>
                % else:
                  <li class="page-item"><a class="page-link" href="?page=${i}">${i}</a></li>
                % endif

              % endfor


              % if posts.has_next:
                <li class="page-item">
                  <a class="page-link" href="?page=${ posts.next_page_number }">Next</a>
                </li>
              % else:
                <li class="page-item disabled">
                  <a class="page-link">Next</a>
                </li>
              % endif


              </ul>
            </nav>

        </%block>

      % endif
    </div>
</%block>

app/post/templates/post/post.html
{% extends 'base.html' %}
{% block title %}{{ post.title }} | Maksim Manylow{% endblock %}
{% block description %}{{ post.excerpt }}{% endblock %}
{% block content %}

<div id="content" class="page-post">

  <article class="post">
    <div class="post-info">
      <h1 class="post-title">{{ post.title }}</h1>
      <div class="post-meta">
        <span class="post-meta-date">{{ post.published_at|date:"M, d Y" }}</span>
        <span class="post-meta-time-to-read">{{post.minutes_to_read}} min read</span>
      </div>
    </div>
    <!--
    <div class="post-image">
      <svg viewBox="0 0 18 7">
        <path fill="#CB3837" d="M0,0v6h5v1h4v-1h9v-6"></path>
        <path fill="#FFF" d="M1,1v4h2v-3h1v3h1v-4h1v5h2v-4h1v2h-1v1h2v-4h1v4h2v-3h1v3h1v-3h1v3h1v-4"></path>
      </svg>
    </div>
  -->
    <div class="post-text">
      {{ post.body|safe }}
      <!--
      <div class="post-tags"><a href="#" class="post-tags-tag">tag1</a><a href="#" class="post-tags-tag">tag2</a></div>
      -->
    </div>
  </article>
  
  <div class="post-comments bg-dark">
      <div id="disqus_thread"></div>
      <script>
      
      /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
      /*
      var disqus_config = function () {
      this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
      };
      */
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://maksimmanylow-com.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                  
  </div>

</div>
{% endblock %}

app/post/templates/post/search.html
{% extends 'base.html' %} 

{% block title %}IT blog of Maksim Manylow, web-dev{% endblock %}
{% block description %}Articles about linux server administration, web development and other things{% endblock %}
{% block content %}
<div id="content" class="page-index">

    <div id="search_bar">
        <form class="form-inline mt-2 mt-md-0 search-form" action="/search">
            <input name="q" class="search-form-input form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" value="{{ query }}">
        </form>
    </div>

  {% for post in posts %}

  <a class="post-link" href="{% url 'post:post' post.slug %}">
    <article class="post">
      <!--
      <div class="post-image">
        <svg viewBox="0 0 18 7">
          <path fill="#CB3837" d="M0,0v6h5v1h4v-1h9v-6"></path>
          <path fill="#FFF" d="M1,1v4h2v-3h1v3h1v-4h1v5h2v-4h1v2h-1v1h2v-4h1v4h2v-3h1v3h1v-3h1v3h1v-4"></path>
        </svg>
      </div>
    -->
      <div class="post-info">
        <h2 class="post-title">{{ post.title }}</h2>
        <div class="post-meta">
          <span class="post-meta-date">{{ post.published_at }}</span>
          <span class="post-meta-time-to-read">{{ post.minutes_to_read }} min read</span>
        </div>
        <div class="post-excerpt">{{ post.excerpt }}</div>
        <div class="post-tags"></div>
      </div>
    </article>
  </a>

  {% empty %}
  <h3>Nothing found.</h3>
  {% endfor %}
 
</section>
{% endblock %}

app/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    {% block stylesheets %}
        <!-- Bootstrap Core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic" rel="stylesheet">
        
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/themes/prism.min.css">
        
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

{% block navigation %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/about">Обо мне</a>
                    </li>
                    <li>
                        <a href="/contacts">Контакты</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
{% endblock %}
<div id="banner"></div>
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            {% block header %}{% endblock %}
            {% block content %}{% endblock %}
            {% block pager %}{% endblock %}

        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

            <div id="sidebar" class="visible-md visible-lg">
                {% block search %}
                    <!-- Blog Search Well -->
                    <div class="well">
                        <h4>Blog Search</h4>
                        <div class="input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                        </div>
                        <!-- /.input-group -->
                    </div>
                {% endblock %}

                <!-- Blog Categories Well -->
                {% block categories %}
                    <div class="well">
                        <h4>Blog Categories</h4>
                                <ul class="list-unstyled">
                                    <li><a href="#">Category Name</a>
                                    </li>
                                    <li><a href="#">Category Name</a>
                                    </li>
                                    <li><a href="#">Category Name</a>
                                    </li>
                                    <li><a href="#">Category Name</a>
                                    </li>
                                </ul>
                    </div>
                {% endblock %}

                {% block sidewidget %}
                    <!-- Side Widget Well -->
                    <div class="well">
                        <h4>Side Widget Well</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
                            accusamus
                            laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                    </div>
                {% endblock %}
            </div>

        </div>

    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->
{% block javascript %}
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/prism.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/components/prism-python.min.js"></script>

{% endblock %}

</body>

</html>